import "./globals.css";
import { Geist, Geist_Mono, Gamja_Flower} from "next/font/google";
import localFont from 'next/font/local';

const uncutSansVar = localFont({
  src: '../assets/fonts/UncutSans-Variable.ttf',
  variable: '--font-uncutSansVar',
});

const uncutSans = localFont({
  src: '../assets/fonts/UncutSans-Regular.woff',
  variable: '--font-uncutSans',
});

const dmMono = localFont({
  src: '../assets/fonts/DMMono-Regular.ttf',
  variable: '--font-dmMono',
});

const martianMono = localFont({
  src: '../assets/fonts/MartianMono-Variable.ttf',
  variable: '--font-martianMono',
});


const gamja = Gamja_Flower({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-gamja",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gamja.variable} ${uncutSansVar.variable} ${uncutSans.variable} ${martianMono.variable} ${dmMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}