import "./globals.css";
import { Geist, Geist_Mono, Odibee_Sans} from "next/font/google";
import localFont from 'next/font/local';

const uncutSansVar = localFont({
  src: '../assets/fonts/UncutSans-Variable.ttf',
  variable: '--font-uncutSansVar',
});

const uncutSans = localFont({
  src: '../assets/fonts/UncutSans-Regular.woff',
  variable: '--font-uncutSans',
});

const dmMono = localFont({
  src: '../assets/fonts/DMMono-Regular.ttf',
  variable: '--font-dmMono',
});

const martianMono = localFont({
  src: '../assets/fonts/MartianMono-Variable.ttf',
  variable: '--font-martianMono',
});


const odibee = Odibee_Sans({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  variable: "--font-odibee",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <bodyuncutSans
        className={`${geistSans.variable} ${geistMono.variable} ${odibee.variable} ${uncutSansVar.variable} ${uncutSans.variable} ${martianMono.variable} ${dmMono.variable} antialiased`}
      >
        {children}
      </bodyuncutSans>
    </html>
  );
}